/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 diamond.glb 
*/
import { useMemo, useEffect } from "react";
import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { useThemeVar, getThemeColor } from "../../lib/themeParser.js";

export const themeDiamondMaterial = (material) => {
  if (!material) return;
  const p1 = getThemeColor("--color-primary-1") || "#ff0240";
  const p2 = getThemeColor("--color-primary-2") || "#9e00a3";

  material.color.set(p1);
  material.attenuationColor.set(p2);
  material.sheenColor.set(p1);
};

export default function Diamond({ ref, materialRef, ...props }) {
  const { nodes } = useGLTF("/assets/diamond.glb");

  const [primary1] = useThemeVar("--color-primary-1");
  const [primary2] = useThemeVar("--color-primary-2");

  const diamondMaterial = useMemo(
    () =>
      new THREE.MeshPhysicalMaterial({
        color: new THREE.Color(primary1),
        transmission: 1,
        opacity: 0.5,
        metalness: 0,
        roughness: 0.2,
        ior: 1.5,
        thickness: 2,
        envMapIntensity: 2,
        dispersion: 2.5,
        attenuationColor: new THREE.Color(primary2),
        attenuationDistance: 0.5,
        iridescence: 0.2,
        iridescenceIOR: 4,
        sheen: 0.3,
        sheenColor: new THREE.Color(primary1),
      }),
    [primary1, primary2],
  );

  useEffect(() => {
    if (materialRef) materialRef.current = diamondMaterial;
  }, [materialRef, diamondMaterial]);

  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        geometry={nodes.Gem003_cell.geometry}
        material={diamondMaterial}
        position={[2.422, 1.934, 5.184]}
      />
      <mesh
        geometry={nodes.Gem003_cell001.geometry}
        material={diamondMaterial}
        position={[2.565, 2.636, 4.915]}
      />
      <mesh
        geometry={nodes.Gem003_cell002.geometry}
        material={diamondMaterial}
        position={[2.453, 2.107, 4.582]}
      />
      <mesh
        geometry={nodes.Gem003_cell003.geometry}
        material={diamondMaterial}
        position={[2.771, 2.145, 4.313]}
      />
      <mesh
        geometry={nodes.Gem003_cell004.geometry}
        material={diamondMaterial}
        position={[2.49, 2.297, 4.245]}
      />
      <mesh
        geometry={nodes.Gem003_cell005.geometry}
        material={diamondMaterial}
        position={[2.731, 2.457, 4.457]}
      />
      <mesh
        geometry={nodes.Gem003_cell006.geometry}
        material={diamondMaterial}
        position={[2.82, 2.091, 4.716]}
      />
      <mesh
        geometry={nodes.Gem003_cell007.geometry}
        material={diamondMaterial}
        position={[3.199, 2.199, 4.698]}
      />
      <mesh
        geometry={nodes.Gem003_cell008.geometry}
        material={diamondMaterial}
        position={[3.042, 2.28, 4.464]}
      />
      <mesh
        geometry={nodes.Gem003_cell009.geometry}
        material={diamondMaterial}
        position={[3.045, 2.489, 4.721]}
      />
      <mesh
        geometry={nodes.Gem003_cell010.geometry}
        material={diamondMaterial}
        position={[3, 2.195, 5.051]}
      />
      <mesh
        geometry={nodes.Gem003_cell011.geometry}
        material={diamondMaterial}
        position={[3.243, 2.42, 5.28]}
      />
      <mesh
        geometry={nodes.Gem003_cell012.geometry}
        material={diamondMaterial}
        position={[3.277, 2.431, 4.95]}
      />
      <mesh
        geometry={nodes.Gem003_cell013.geometry}
        material={diamondMaterial}
        position={[3.052, 2.627, 5.11]}
      />
      <mesh
        geometry={nodes.Gem003_cell014.geometry}
        material={diamondMaterial}
        position={[2.853, 2.303, 5.376]}
      />
      <mesh
        geometry={nodes.Gem003_cell015.geometry}
        material={diamondMaterial}
        position={[2.836, 2.626, 5.692]}
      />
      <mesh
        geometry={nodes.Gem003_cell016.geometry}
        material={diamondMaterial}
        position={[3.099, 2.626, 5.462]}
      />
      <mesh
        geometry={nodes.Gem003_cell017.geometry}
        material={diamondMaterial}
        position={[2.785, 2.78, 5.384]}
      />
      <mesh
        geometry={nodes.Gem003_cell018.geometry}
        material={diamondMaterial}
        position={[2.503, 2.439, 5.53]}
      />
      <mesh
        geometry={nodes.Gem003_cell019.geometry}
        material={diamondMaterial}
        position={[2.25, 2.734, 5.682]}
      />
      <mesh
        geometry={nodes.Gem003_cell020.geometry}
        material={diamondMaterial}
        position={[2.581, 2.779, 5.667]}
      />
      <mesh
        geometry={nodes.Gem003_cell021.geometry}
        material={diamondMaterial}
        position={[2.374, 2.843, 5.356]}
      />
      <mesh
        geometry={nodes.Gem003_cell022.geometry}
        material={diamondMaterial}
        position={[2.157, 2.431, 5.397]}
      />
      <mesh
        geometry={nodes.Gem003_cell023.geometry}
        material={diamondMaterial}
        position={[1.823, 2.649, 5.288]}
      />
      <mesh
        geometry={nodes.Gem003_cell024.geometry}
        material={diamondMaterial}
        position={[2.045, 2.808, 5.464]}
      />
      <mesh
        geometry={nodes.Gem003_cell025.geometry}
        material={diamondMaterial}
        position={[2.06, 2.799, 5.109]}
      />
      <mesh
        geometry={nodes.Gem003_cell026.geometry}
        material={diamondMaterial}
        position={[1.986, 2.352, 5.047]}
      />
      <mesh
        geometry={nodes.Gem003_cell027.geometry}
        material={diamondMaterial}
        position={[1.791, 2.44, 4.7]}
      />
      <mesh
        geometry={nodes.Gem003_cell028.geometry}
        material={diamondMaterial}
        position={[1.795, 2.676, 4.936]}
      />
      <mesh
        geometry={nodes.Gem003_cell029.geometry}
        material={diamondMaterial}
        position={[2.051, 2.663, 4.717]}
      />
      <mesh
        geometry={nodes.Gem003_cell030.geometry}
        material={diamondMaterial}
        position={[2.114, 2.223, 4.707]}
      />
      <mesh
        geometry={nodes.Gem003_cell031.geometry}
        material={diamondMaterial}
        position={[2.174, 2.256, 4.313]}
      />
      <mesh
        geometry={nodes.Gem003_cell032.geometry}
        material={diamondMaterial}
        position={[1.986, 2.464, 4.442]}
      />
      <mesh
        geometry={nodes.Gem003_cell033.geometry}
        material={diamondMaterial}
        position={[2.331, 2.54, 4.463]}
      />
    </group>
  );
}

useGLTF.preload("/assets/diamond.glb");
